# Generated by Django 3.2.8 on 2022-04-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='res_done',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservations_id', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('person_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='res_date',
        ),
    ]
