# Generated by Django 3.2.8 on 2022-04-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220415_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='res_done',
            name='person_rank',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
