# Generated by Django 3.2.8 on 2022-05-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_res_done_person_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancel_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_wantcancel_id', models.CharField(max_length=200)),
                ('person_substitute_id', models.CharField(max_length=200)),
                ('reservations_id', models.CharField(max_length=200)),
            ],
        ),
    ]
