# Generated by Django 3.2.8 on 2022-05-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_cancel_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancel_request',
            name='response_to_request',
            field=models.CharField(default='pending', max_length=200),
            preserve_default=False,
        ),
    ]
