# Generated by Django 3.2.8 on 2022-05-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_rename_day_reservations_day_in_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='res_done',
            name='date',
        ),
    ]
