# Generated by Django 3.2.8 on 2022-05-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_person_reduce_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_reduce_shift',
            name='person_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
