# Generated by Django 3.2.8 on 2022-05-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_person_reduce_shift_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='archive_res_done',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservations_id', models.CharField(max_length=200)),
                ('person_id', models.CharField(max_length=200)),
                ('month_number', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
