# Generated by Django 3.2.8 on 2022-05-22 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_archive_res_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='fname',
            new_name='fullName',
        ),
        migrations.RemoveField(
            model_name='person',
            name='lname',
        ),
    ]
